---
# tasks file for create_asg

- name: check if the keyfile exists
  stat:  
    path: "./keypair-wpstack.pem"
  register: keyfile

- debug:
    msg: keyfile exists
  when: keyfile.stat.exists

- name: create aws ec2 keypair | wp stack
  ec2_key:
    name: wp-stack-key
    region: "{{ aws_region }}"
  register: aws_keypair

- name: save private key | wp stack
  copy:
    content: "{{ aws_keypair.key.private_key }}"
    dest: "./keypair-wpstack.pem"
    mode: "0600"
  when: aws_keypair.changed

#use of ports was introduced in ansible version 2.4, so if you are getting errors on this step please upgrade to ansible version 2.4
- name: create security group | wp stack
  ec2_group:
    name: "{{ aws_security_group }}" 
    description: wp stack security group with out side acccess enabled 
    vpc_id: "{{ aws_vpc_id }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        ports: 22
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        ports:
          - 8080
          - 3000
          - 9090
        cidr_ip: 0.0.0.0/0


- name: create launch config | wp stack
  ec2_lc:
    name: wp_stack_lc
    image_id: "{{ aws_ami_id }}"
    key_name: wp-stack-key
    region: "{{ aws_region }}"
    security_groups: "{{ aws_security_group }}"
    instance_type: "{{ aws_instance_type }}"
    user_data_path: "roles/create_asg/files/user_data_ubuntu.sh"
    assign_public_ip: yes

- name: create auto scaling group | wp stack
  ec2_asg:
    name: wp_stack_asg
    launch_config_name: wp_stack_lc
    health_check_period: 60
    health_check_type: EC2
    replace_all_instances: yes
    min_size: 1
    max_size: 2
    desired_capacity: 1
    vpc_zone_identifier: ['subnet-7f4c9927', 'subnet-aad1bbce']
    region: "{{ aws_region }}"
    tags: 
      - Name: wp_stack_asg
      - env: dev
        propagate_at_launch: true
  register: wp_asg


- ec2_instance_facts:
    filters:
      "tag:Name": wp_stack_asg
    region: "{{ aws_region }}"
  register: ec2

- name: Wait for 8080 to come up
  wait_for:
    host: "{{ ec2.instances[0].public_dns_name }}"
    port: 8080
    delay: 60
    timeout: 320
    state: started

- include: cleanup.yaml
  tags: destroy
